variable "component" {}
variable "env" {}
variable "instance_type" {}
variable "sg_subnet_cidr" {}
variable "tags" {}
variable "vpc_id" {}
variable "subnet_id" {}
variable "bastion_host" {}
variable "zone_id" {}
variable "kms_key_id" {}